sudo: required

language: node_js
node_js:
  - 13

branches:
  only:
    - master

services:
  - docker

script:
  - docker-compose -f docker-compose.yml up -d --build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
  - docker-compose -f docker-compose.yml push
  - scp -o "StrictHostKeyChecking no" docker-compose.production.yml ubuntu@mrxzh.com:/home/ubuntu/ossian-board/
  - ssh -o "StrictHostKeyChecking no" ubuntu@mrxzh.com "cd /home/ubuntu/ossian-board/;docker-compose -f docker-compose.production.yml pull;docker-compose -f docker-compose.production.yml up -d;exit"