version: "3"
services:
    db:
        image: mongo:4.0-bionic
        ports:
            - "37017:27017"
        restart: always
    static:
        build: ./frontend/
        ports:
            - "4000:80"
        restart: always
    backend:
        build: ./Logger/
        restart: always