version: "3"
services:
    db:
        image: mongo:4.4-bionic
        ports:
            - "37017:27017"
        restart: always
        volumes:
            - /root/mongodata:/data/db
        command: mongod --wiredTigerCacheSizeGB=1.0
    static:
        image: registry.cn-hangzhou.aliyuncs.com/ossian/ossian-board-static
        ports:
            - "4000:80"
            - "4001:90"
        restart: always
    backend:
        image: registry.cn-hangzhou.aliyuncs.com/ossian/ossian-board-backend
        restart: always